#!/bin/bash -l

# This script does a bfb comparison of files in two provided directories.
dir1=$1
dir2=$2

homedir=`pwd`
rm failed_list passed_list notfound_list
pass=0
fail=0
notfound=0

touch failed_list
touch passed_list
touch notfound_list
cd $dir1
echo ""
Files=*.nc
        for f in $Files
        do
                if test -f $dir2/$f
                then

                        #nccmp -d   $f  $dir2/$f
                        nccmp -dSqf  $f  $dir2/$f

                        if [ "$?" != "0" ]
                        then
                                echo "$f" >> $homedir/failed_list
				fail=`expr $fail + 1`
				echo "$f"
				echo ""
                        else
                                echo "$f" >> $homedir/passed_list
				pass=`expr $pass + 1`
                        fi
		else
			echo "$f" >> $homedir/notfound_list
			notfound=`expr $notfound + 1`
                fi
        done
cd $homedir

echo "passed $pass  failed $fail nomatch $notfound" > bfb_results
echo ""


